# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-01 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
