# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-01 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_business_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contact',
            new_name='location',
        ),
    ]
