# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-04 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
